"""A small film-language guide: shot sizes, camera angles, camera moves,
lenses and focus, light and composition. Each entry carries a name and a
plain explanation (English and Spanish), when to use it, and the English
words that ask an image or video model for it. The studio shows it as a
guide, offers it in prompts (typing "/plano", "/shot"...) and adds the
chosen terms to a picture's or a clip's prompt (`camera` options)."""

from __future__ import annotations

from typing import Any, Optional

CATEGORIES: dict[str, dict[str, Any]] = {
    "shot": {"en": "Shot size", "es": "Tipo de plano", "aliases": ["plano", "planos", "shot", "shots", "encuadre", "framing"]},
    "angle": {"en": "Camera angle", "es": "Ángulo de cámara", "aliases": ["angulo", "ángulo", "angle", "angulos"]},
    "move": {"en": "Camera move", "es": "Movimiento de cámara", "aliases": ["movimiento", "mov", "move", "camara", "cámara", "camera"]},
    "lens": {"en": "Lens and focus", "es": "Lente y foco", "aliases": ["lente", "lens", "foco", "focus", "optica", "óptica"]},
    "light": {"en": "Light", "es": "Luz", "aliases": ["luz", "light", "iluminacion", "iluminación", "lighting"]},
    "composition": {"en": "Composition", "es": "Composición", "aliases": ["composicion", "composición", "composition", "comp"]},
}


def _e(id_: str, cat: str, en: str, es: str, what_en: str, what_es: str, when_en: str, when_es: str,
       prompt: str, aliases: tuple[str, ...] = (), video_only: bool = False) -> dict[str, Any]:
    return {"id": id_, "category": cat, "name": {"en": en, "es": es}, "what": {"en": what_en, "es": what_es},
            "when": {"en": when_en, "es": when_es}, "prompt": prompt, "aliases": list(aliases), "video_only": video_only}


ENTRIES: list[dict[str, Any]] = [
    # ------------------------------------------------------------ shot sizes
    _e("extreme_wide", "shot", "Extreme wide shot", "Gran plano general",
       "The place is the subject: the person is a speck in a huge landscape or city.",
       "El lugar es el protagonista: la persona es un punto en un paisaje o una ciudad enorme.",
       "Open a story or a scene, show scale, loneliness or how small someone is.",
       "Para abrir una historia o escena, enseñar la escala, la soledad o lo pequeño que es alguien.",
       "extreme wide shot, tiny figure in a vast landscape", ("egp", "xws", "establishing", "situacion", "situación")),
    _e("wide", "shot", "Wide shot", "Plano general",
       "The whole body and plenty of the place around it.",
       "El cuerpo entero y buena parte del lugar a su alrededor.",
       "Place the character in the scene, show movement and blocking.",
       "Situar al personaje en el escenario, enseñar el movimiento y la puesta en escena.",
       "wide shot, full body visible with lots of the surroundings", ("pg", "ws", "general")),
    _e("full", "shot", "Full shot", "Plano entero",
       "Head to toes, filling the frame from top to bottom.",
       "De la cabeza a los pies, llenando el cuadro de arriba abajo.",
       "Show an outfit, a pose or a dance.",
       "Enseñar un vestuario, una pose o un baile.",
       "full shot, head to toe, the whole figure fills the frame", ("pe", "fs", "entero", "cuerpo entero")),
    _e("cowboy", "shot", "Medium-full (cowboy) shot", "Plano americano",
       "From mid-thigh or the knees up. Named after westerns, where it showed the gun belt.",
       "Desde medio muslo o las rodillas. Viene de los westerns: dejaba ver la pistolera.",
       "Two or three people talking, a confident stance.",
       "Dos o tres personas hablando, una pose con presencia.",
       "medium full shot framed from the knees up, cowboy shot", ("pa", "americano", "tres cuartos")),
    _e("medium", "shot", "Medium shot", "Plano medio",
       "From the waist up: face and hands are both readable.",
       "De cintura para arriba: se leen la cara y las manos.",
       "Dialogue, singing with gestures, the everyday default.",
       "Diálogos, cantar con gestos; el plano de uso diario.",
       "medium shot, framed from the waist up", ("pm", "ms", "medio", "cintura")),
    _e("medium_close", "shot", "Medium close-up", "Plano medio corto",
       "From the chest up: the face leads, a bit of clothing frames it.",
       "Del pecho para arriba: manda la cara y un poco de ropa la enmarca.",
       "Emotional lines, a singer at the microphone, interviews.",
       "Frases con emoción, alguien cantando al micro, entrevistas.",
       "medium close-up, framed from the chest up", ("pmc", "mcu", "pecho")),
    _e("close_up", "shot", "Close-up", "Primer plano",
       "Head and the top of the shoulders: the face fills the frame.",
       "La cabeza y el arranque de los hombros: la cara llena el cuadro.",
       "Feelings, reactions, the key moment of a scene.",
       "Sentimientos, reacciones, el momento clave de la escena.",
       "close-up of the face, head and shoulders filling the frame", ("pp", "cu", "primer", "cara")),
    _e("extreme_close_up", "shot", "Extreme close-up", "Primerísimo primer plano",
       "Only part of the face: the eyes, or the mouth.",
       "Solo una parte de la cara: los ojos o la boca.",
       "Tension, a decision, a detail that matters (a tear, a smile).",
       "Tensión, una decisión, un detalle que importa (una lágrima, una sonrisa).",
       "extreme close-up on the eyes, only part of the face visible", ("ppp", "ecu", "ojos", "macro cara")),
    _e("detail", "shot", "Insert / detail shot", "Plano detalle",
       "An object or a hand, very close: the microphone, a ring, a ticket.",
       "Un objeto o una mano muy de cerca: el micrófono, un anillo, una entrada.",
       "Point at something the audience must notice; cutaways in a music video.",
       "Señalar algo que el público debe ver; recursos en un videoclip.",
       "insert detail shot of a hand holding an object, very close", ("pd", "insert", "detalle", "objeto")),
    _e("over_shoulder", "shot", "Over-the-shoulder shot", "Plano sobre el hombro",
       "We look at one person past the blurred shoulder and head of another.",
       "Vemos a una persona por encima del hombro y la nuca, desenfocados, de otra.",
       "Conversations (shot / reverse shot), confrontations.",
       "Conversaciones (plano y contraplano), enfrentamientos.",
       "over-the-shoulder shot, blurred shoulder and back of a head in the foreground", ("ots", "hombro", "contraplano", "escorzo")),
    _e("two_shot", "shot", "Two shot", "Plano de dos",
       "Two people share the frame.",
       "Dos personas comparten el cuadro.",
       "Relationships, duets, a band's frontline.",
       "Relaciones, duetos, la primera fila de un grupo.",
       "two shot, two people side by side in the same frame", ("dos", "pareja", "duo", "dúo")),
    _e("pov", "shot", "Point-of-view shot", "Plano subjetivo",
       "The camera is the character's eyes: we may see their hands.",
       "La cámara son los ojos del personaje: a veces vemos sus manos.",
       "Put the audience in someone's place: fear, discovery, a crowd seen from the stage.",
       "Poner al público en el lugar de alguien: miedo, descubrimiento, el público visto desde el escenario.",
       "first-person point of view shot, the character's own hands in the foreground", ("subjetivo", "primera persona", "pov")),

    # --------------------------------------------------------------- angles
    _e("eye_level", "angle", "Eye level", "Ángulo normal",
       "The camera at the height of the eyes: neutral.",
       "La cámara a la altura de los ojos: neutral.",
       "Most dialogue; to be honest with the viewer.",
       "La mayoría de diálogos; para ser sincero con quien mira.",
       "eye-level camera angle", ("normal", "neutro", "altura de los ojos")),
    _e("low_angle", "angle", "Low angle", "Contrapicado",
       "The camera looks up at the subject.",
       "La cámara mira al sujeto desde abajo.",
       "Power, threat, a hero or a monster; a singer looking huge on stage.",
       "Poder, amenaza, un héroe o un monstruo; alguien enorme sobre el escenario.",
       "low angle shot looking up at the subject", ("contrapicado", "desde abajo", "low")),
    _e("high_angle", "angle", "High angle", "Picado",
       "The camera looks down at the subject.",
       "La cámara mira al sujeto desde arriba.",
       "Weakness, being watched, someone overwhelmed.",
       "Debilidad, sentirse observado, alguien superado.",
       "high angle shot looking down at the subject", ("picado", "desde arriba", "high")),
    _e("overhead", "angle", "Overhead (bird's eye)", "Cenital",
       "Straight down from above, like a map.",
       "Justo desde arriba, como un mapa.",
       "Patterns, choreography, a body lying down, a table.",
       "Patrones, coreografías, alguien tumbado, una mesa.",
       "overhead top-down shot, bird's eye view", ("cenital", "vista de pajaro", "pájaro", "top down")),
    _e("worms_eye", "angle", "Worm's eye", "Nadir",
       "From the floor, almost straight up.",
       "Desde el suelo, casi en vertical hacia arriba.",
       "Towering buildings or figures, the extreme version of a low angle.",
       "Edificios o figuras gigantes; un contrapicado llevado al extremo.",
       "worm's eye view from the ground looking straight up", ("nadir", "suelo", "worm")),
    _e("dutch", "angle", "Dutch angle", "Plano aberrante (holandés)",
       "The camera is tilted, so the horizon is crooked.",
       "La cámara está inclinada y el horizonte se tuerce.",
       "Unease, madness, drunkenness, horror.",
       "Inquietud, locura, borrachera, terror.",
       "dutch angle, tilted camera, crooked horizon", ("holandes", "holandés", "aberrante", "inclinado", "canted")),

    # ---------------------------------------------------------------- moves
    _e("static", "move", "Static shot", "Plano fijo",
       "The camera does not move; only the subject does.",
       "La cámara no se mueve; solo se mueve el sujeto.",
       "Let a performance breathe; calm or dread.",
       "Dejar respirar una interpretación; calma o inquietud.",
       "static locked-off camera, no camera movement", ("fijo", "tripode", "trípode", "static"), True),
    _e("pan", "move", "Pan", "Panorámica horizontal",
       "The camera turns left or right on the spot.",
       "La cámara gira a izquierda o derecha sin desplazarse.",
       "Follow someone walking, reveal what is next to them.",
       "Seguir a alguien que camina, descubrir lo que hay a su lado.",
       "slow camera pan from left to right", ("panoramica", "panorámica", "pan", "girar"), True),
    _e("tilt", "move", "Tilt", "Panorámica vertical",
       "The camera tilts up or down on the spot.",
       "La cámara cabecea hacia arriba o hacia abajo sin desplazarse.",
       "Reveal someone tall from feet to face, or a building.",
       "Descubrir a alguien alto de los pies a la cara, o un edificio.",
       "camera tilts up from the feet to the face", ("tilt", "vertical", "cabeceo"), True),
    _e("dolly_in", "move", "Dolly in (push in)", "Travelling de avance",
       "The camera travels towards the subject.",
       "La cámara se acerca al sujeto desplazándose.",
       "Build intensity, a realisation, the chorus kicking in.",
       "Subir la intensidad, una revelación, cuando entra el estribillo.",
       "slow dolly in, the camera pushes in towards the subject", ("avance", "acercar", "push in", "dolly in"), True),
    _e("dolly_out", "move", "Dolly out (pull back)", "Travelling de retroceso",
       "The camera travels away and reveals more of the place.",
       "La cámara se aleja y descubre más del lugar.",
       "Endings, loneliness, a reveal of where we really are.",
       "Finales, soledad, descubrir dónde estamos de verdad.",
       "slow dolly out, the camera pulls back to reveal the surroundings", ("retroceso", "alejar", "pull back", "dolly out"), True),
    _e("truck", "move", "Truck (lateral travelling)", "Travelling lateral",
       "The camera slides sideways; near things pass faster than far ones.",
       "La cámara se desliza de lado; lo cercano pasa más rápido que lo lejano.",
       "Walk alongside someone, pass along a line of people or objects.",
       "Acompañar a alguien que camina, recorrer una fila de personas u objetos.",
       "lateral tracking shot, the camera slides sideways with parallax", ("lateral", "truck", "deslizar"), True),
    _e("tracking", "move", "Tracking shot", "Travelling de seguimiento",
       "The camera follows the subject, keeping them in frame.",
       "La cámara sigue al sujeto y lo mantiene en cuadro.",
       "Energy, walking and talking, chases.",
       "Energía, caminar hablando, persecuciones.",
       "tracking shot following the subject as they walk", ("seguimiento", "seguir", "follow", "steadicam"), True),
    _e("crane", "move", "Crane (jib) up", "Grúa",
       "The camera rises (or falls) through the air.",
       "La cámara sube (o baja) por el aire.",
       "Big openings and endings, a stage seen from above the crowd.",
       "Grandes aperturas y finales, el escenario visto por encima del público.",
       "crane shot rising up and over the scene", ("grua", "grúa", "jib", "subir"), True),
    _e("orbit", "move", "Orbit (arc shot)", "Travelling circular",
       "The camera circles around the subject.",
       "La cámara gira alrededor del sujeto.",
       "Make a moment feel epic, a hero shot, a kiss, a solo.",
       "Hacer épico un momento: un plano de héroe, un beso, un solo.",
       "camera orbits around the subject in a smooth arc", ("orbita", "órbita", "arco", "circular", "360"), True),
    _e("handheld", "move", "Handheld", "Cámara en mano",
       "Small shakes, like a person holding the camera.",
       "Pequeños temblores, como si alguien sujetara la cámara.",
       "Documentary feel, nervousness, live concerts.",
       "Aire documental, nervios, conciertos en directo.",
       "handheld camera with subtle natural shake", ("mano", "handheld", "temblor", "documental"), True),
    _e("zoom_in", "move", "Zoom in", "Zoom",
       "The lens magnifies without the camera moving: the background grows with the subject.",
       "La lente amplía sin que la cámara se mueva: el fondo crece a la vez que el sujeto.",
       "70s style, a sudden focus on someone, comedy.",
       "Estilo setentero, fijarse de golpe en alguien, comedia.",
       "slow optical zoom in", ("zoom", "ampliar"), True),
    _e("whip_pan", "move", "Whip pan", "Barrido",
       "A pan so fast the image blurs.",
       "Una panorámica tan rápida que la imagen se emborrona.",
       "Energetic cuts between two places, comedy beats, transitions on the beat.",
       "Cortes con energía entre dos sitios, golpes de humor, transiciones al ritmo.",
       "fast whip pan with motion blur", ("barrido", "whip", "rapido", "rápido"), True),
    _e("dolly_zoom", "move", "Dolly zoom (vertigo)", "Efecto vértigo",
       "The camera moves back while zooming in: the subject stays, the background stretches.",
       "La cámara retrocede mientras hace zoom: el sujeto se queda igual y el fondo se estira.",
       "Shock, dizziness, a world falling apart.",
       "Impacto, mareo, el mundo que se viene abajo.",
       "dolly zoom vertigo effect, the background stretches while the subject stays the same size", ("vertigo", "vértigo", "hitchcock", "dolly zoom"), True),
    _e("drone", "move", "Drone flyover", "Plano de dron",
       "The camera flies forward high over the place.",
       "La cámara vuela hacia delante por encima del lugar.",
       "Openings, travel, cities at night.",
       "Aperturas, viajes, ciudades de noche.",
       "aerial drone shot flying forward over the landscape", ("dron", "aereo", "aéreo", "fpv", "drone"), True),

    # --------------------------------------------------------- lens & focus
    _e("ultra_wide", "lens", "Wide-angle lens (14-24 mm)", "Gran angular (14-24 mm)",
       "Sees a lot; near things look big and far things small; lines bend at the edges.",
       "Abarca mucho; lo cercano parece enorme y lo lejano pequeño; las líneas se curvan en los bordes.",
       "Tight rooms, energy, skate and hip-hop videos, a face pushed into the lens.",
       "Sitios estrechos, energía, vídeos de skate o hip-hop, una cara pegada a la lente.",
       "shot on a 16mm ultra wide-angle lens, exaggerated perspective", ("angular", "gran angular", "wide", "16mm", "24mm")),
    _e("normal", "lens", "Normal lens (35-50 mm)", "Objetivo normal (35-50 mm)",
       "Close to how the eye sees: natural proportions.",
       "Parecido a como ve el ojo: proporciones naturales.",
       "Honest, natural images; most narrative scenes.",
       "Imágenes naturales y sinceras; la mayoría de escenas.",
       "shot on a 50mm lens, natural perspective", ("normal", "50mm", "35mm")),
    _e("telephoto", "lens", "Telephoto (85-200 mm)", "Teleobjetivo (85-200 mm)",
       "Brings the far close, flattens distances and blurs the background.",
       "Acerca lo lejano, aplana las distancias y desenfoca el fondo.",
       "Flattering portraits, spying, crowds packed together, sunsets with a huge sun.",
       "Retratos favorecedores, espiar, multitudes apretadas, atardeceres con un sol enorme.",
       "shot on a 135mm telephoto lens, compressed background", ("tele", "teleobjetivo", "85mm", "135mm", "telephoto")),
    _e("macro", "lens", "Macro", "Macro",
       "Tiny things at huge size, with very little in focus.",
       "Cosas diminutas a gran tamaño, con muy poco enfocado.",
       "Textures, drops, eyes, insects, product details.",
       "Texturas, gotas, ojos, insectos, detalles de producto.",
       "macro photography, extreme magnification, tiny depth of field", ("macro",)),
    _e("fisheye", "lens", "Fisheye", "Ojo de pez",
       "An extreme wide angle that bends everything into a circle.",
       "Un gran angular extremo que curva todo en un círculo.",
       "Skate, 90s rap, surreal or funny moments.",
       "Skate, rap noventero, momentos surrealistas o graciosos.",
       "fisheye lens, strong barrel distortion", ("ojo de pez", "fisheye", "pez")),
    _e("anamorphic", "lens", "Anamorphic", "Anamórfico",
       "The cinema widescreen look: oval bokeh and horizontal blue flares.",
       "El aspecto panorámico de cine: bokeh ovalado y destellos horizontales azules.",
       "Make it feel like a feature film; night scenes with lights.",
       "Que parezca una película de cine; noches con luces.",
       "anamorphic lens, 2.39:1 widescreen, horizontal lens flares, oval bokeh", ("anamorfico", "anamórfico", "cinemascope", "flare")),
    _e("shallow_focus", "lens", "Shallow depth of field", "Poca profundidad de campo",
       "Only the subject is sharp; the background melts into blur (bokeh).",
       "Solo el sujeto está nítido; el fondo se deshace en desenfoque (bokeh).",
       "Isolate someone, portraits, dreamy looks.",
       "Aislar a alguien, retratos, aspecto de ensueño.",
       "shallow depth of field, creamy bokeh background, f/1.4", ("bokeh", "desenfoque", "poca profundidad", "f1.4")),
    _e("deep_focus", "lens", "Deep focus", "Profundidad de campo amplia",
       "Everything sharp, from the foreground to the horizon.",
       "Todo nítido, del primer término al horizonte.",
       "Busy scenes where everything matters, landscapes.",
       "Escenas llenas donde todo importa, paisajes.",
       "deep focus, everything sharp from foreground to background, f/11", ("todo enfocado", "deep", "f11")),
    _e("rack_focus", "lens", "Rack focus", "Cambio de foco",
       "The focus moves from one thing to another during the shot.",
       "El foco pasa de una cosa a otra durante el plano.",
       "Shift attention: from a hand to a face, from the singer to the crowd.",
       "Mover la atención: de una mano a una cara, de quien canta al público.",
       "rack focus from the foreground to the background", ("cambio de foco", "rack", "pull focus"), True),

    # ---------------------------------------------------------------- light
    _e("high_key", "light", "High key", "Clave alta",
       "Bright and even, few shadows.",
       "Luminosa y uniforme, pocas sombras.",
       "Pop, comedy, beauty, clean product shots.",
       "Pop, comedia, belleza, producto limpio.",
       "high-key lighting, bright and evenly lit, soft shadows", ("clave alta", "luminoso", "high key")),
    _e("low_key", "light", "Low key", "Clave baja",
       "Mostly dark with a single strong light.",
       "Casi todo oscuro con una sola luz fuerte.",
       "Drama, noir, horror, intimate songs.",
       "Drama, cine negro, terror, canciones íntimas.",
       "low-key lighting, deep shadows, single hard key light", ("clave baja", "oscuro", "noir", "low key")),
    _e("chiaroscuro", "light", "Chiaroscuro (side light)", "Claroscuro",
       "Light from one side: half the face lit, half in shadow.",
       "Luz de un lado: media cara iluminada y media en sombra.",
       "Doubt, two-faced characters, painterly portraits.",
       "Dudas, personajes con doble cara, retratos de cuadro.",
       "chiaroscuro side lighting, half of the face in shadow", ("claroscuro", "lateral", "rembrandt", "side light")),
    _e("rim_light", "light", "Rim light (backlight)", "Contraluz de recorte",
       "A light behind the subject draws a bright outline around them.",
       "Una luz detrás del sujeto dibuja un contorno brillante a su alrededor.",
       "Separate from a dark background, stage and concert looks, hair glowing.",
       "Separar de un fondo oscuro, aspecto de escenario y concierto, pelo brillante.",
       "strong rim light outlining the silhouette from behind", ("contraluz", "recorte", "rim", "backlight")),
    _e("silhouette", "light", "Silhouette", "Silueta",
       "The subject is black against a bright background.",
       "El sujeto es negro contra un fondo luminoso.",
       "Mystery, iconic poses, sunsets, a figure in a doorway.",
       "Misterio, poses icónicas, atardeceres, una figura en una puerta.",
       "dark silhouette against a bright background", ("silueta", "silhouette")),
    _e("golden_hour", "light", "Golden hour", "Hora dorada",
       "Low warm sun just after sunrise or before sunset.",
       "Sol bajo y cálido justo después del amanecer o antes del atardecer.",
       "Romance, nostalgia, summer songs.",
       "Romance, nostalgia, canciones de verano.",
       "golden hour sunlight, warm low sun, long soft shadows", ("hora dorada", "atardecer", "golden", "sunset")),
    _e("blue_hour", "light", "Blue hour", "Hora azul",
       "The deep blue light just after sunset, with city lights coming on.",
       "La luz azul intensa justo después de ponerse el sol, con las luces de la ciudad encendiéndose.",
       "Melancholy, calm cities, the start of a night out.",
       "Melancolía, ciudades tranquilas, el principio de una noche de fiesta.",
       "blue hour twilight, deep blue sky, city lights turning on", ("hora azul", "crepusculo", "crepúsculo", "twilight")),
    _e("neon", "light", "Neon", "Neón",
       "Saturated coloured lights, usually magenta and cyan, on a dark night.",
       "Luces de color saturadas, normalmente magenta y cian, en una noche oscura.",
       "Clubs, synthwave, cyberpunk, rainy streets.",
       "Discotecas, synthwave, cyberpunk, calles mojadas.",
       "neon lighting, magenta and cyan glow, wet reflective streets", ("neon", "neón", "cyberpunk", "synthwave")),
    _e("practical", "light", "Practical lights", "Luces prácticas",
       "The light comes from lamps, candles or screens that are in the shot.",
       "La luz sale de lámparas, velas o pantallas que se ven en el plano.",
       "Realism, cosy or eerie interiors, night scenes.",
       "Realismo, interiores acogedores o inquietantes, escenas de noche.",
       "lit only by practical lights visible in the frame, lamps and candles", ("practicas", "prácticas", "practical", "velas", "lamparas")),
    _e("soft_light", "light", "Soft light", "Luz suave",
       "A large, diffused source: gentle shadows and smooth skin.",
       "Una fuente grande y difusa: sombras suaves y piel suave.",
       "Beauty, calm, flattering close-ups.",
       "Belleza, calma, primeros planos favorecedores.",
       "soft diffused lighting, large softbox, gentle shadows", ("suave", "difusa", "softbox", "soft")),

    # ---------------------------------------------------------- composition
    _e("rule_of_thirds", "composition", "Rule of thirds", "Regla de los tercios",
       "Split the frame in three both ways and put the subject on a line or a crossing.",
       "Divide el cuadro en tres en las dos direcciones y pon al sujeto en una línea o un cruce.",
       "Balanced, natural images with room to breathe.",
       "Imágenes equilibradas y naturales, con aire.",
       "composition following the rule of thirds, subject off-centre", ("tercios", "thirds")),
    _e("symmetry", "composition", "Centred symmetry", "Simetría centrada",
       "The subject in the exact centre, both halves mirror each other.",
       "El sujeto en el centro exacto y las dos mitades como un espejo.",
       "Order, power, a stylised or obsessive look.",
       "Orden, poder, un aire estilizado u obsesivo.",
       "perfectly symmetrical centred composition", ("simetria", "simetría", "centrado", "symmetry")),
    _e("leading_lines", "composition", "Leading lines", "Líneas guía",
       "Roads, rails or walls that lead the eye to the subject.",
       "Carreteras, raíles o paredes que llevan la mirada al sujeto.",
       "Depth, journeys, pointing at what matters.",
       "Profundidad, viajes, señalar lo importante.",
       "strong leading lines converging on the subject", ("lineas", "líneas", "guia", "guía", "leading")),
    _e("negative_space", "composition", "Negative space", "Espacio negativo",
       "A small subject surrounded by a lot of empty space.",
       "Un sujeto pequeño rodeado de mucho espacio vacío.",
       "Loneliness, minimalism, room for a title.",
       "Soledad, minimalismo, hueco para un título.",
       "minimalist composition with lots of negative space", ("espacio negativo", "vacio", "vacío", "minimal")),
    _e("frame_in_frame", "composition", "Frame within a frame", "Marco dentro del marco",
       "A door, window or mirror frames the subject inside the shot.",
       "Una puerta, una ventana o un espejo enmarcan al sujeto dentro del plano.",
       "Feeling trapped, voyeurism, focus.",
       "Sensación de encierro, mirar a escondidas, concentrar la atención.",
       "framed through a doorway, frame within a frame", ("marco", "puerta", "ventana", "frame")),
    _e("foreground_layers", "composition", "Foreground layers", "Capas en primer término",
       "Something blurred close to the lens in front of the subject adds depth.",
       "Algo desenfocado cerca de la lente, delante del sujeto, añade profundidad.",
       "Peeking through a crowd, leaves, bars; cinematic depth.",
       "Mirar entre el público, hojas o barrotes; profundidad de cine.",
       "out-of-focus foreground elements framing the subject, layered depth", ("primer termino", "primer término", "capas", "foreground")),
]

BY_ID = {e["id"]: e for e in ENTRIES}


def _norm(s: str) -> str:
    import unicodedata
    return "".join(c for c in unicodedata.normalize("NFKD", s.lower()) if not unicodedata.combining(c))


def search(query: str = "", category: Optional[str] = None, lang: str = "es") -> list[dict[str, Any]]:
    """Entries whose category, names or aliases match the query (accents and
    case ignored); a query that names a category ("plano", "luz") lists it."""
    q = _norm(query.strip().lstrip("/"))
    items = [e for e in ENTRIES if not category or e["category"] == category]
    if not q:
        return items
    for cat, info in CATEGORIES.items():
        if q in [_norm(a) for a in info["aliases"]] or q in (_norm(info["en"]), _norm(info["es"])):
            return [e for e in items if e["category"] == cat]
    import re

    def score(e: dict[str, Any]) -> int:
        names = [_norm(e["name"]["es"]), _norm(e["name"]["en"])]
        if any(n.startswith(q) for n in names):
            return 0
        if any(w.startswith(q) for n in names for w in re.split(r"[\s(/-]+", n)):
            return 1
        if any(q in n for n in names):
            return 2
        aliases = [_norm(e["id"])] + [_norm(a) for a in e["aliases"]]
        if any(a.startswith(q) for a in aliases):
            return 3
        return 4 if any(q in a for a in aliases) else 9

    scored = [(score(e), i, e) for i, e in enumerate(items)]
    return [e for sc, _, e in sorted(scored, key=lambda x: (x[0], x[1])) if sc < 9]


CAMERA_KEYS = ("shot", "angle", "move", "lens", "light", "composition")


def camera_prompt(camera: Optional[dict[str, Any]], video: bool = False) -> str:
    """The English terms for a {shot, angle, move, lens, light, composition}
    choice; moves only for clips. Unknown ids are ignored."""
    if not isinstance(camera, dict):
        return ""
    parts = []
    for key in CAMERA_KEYS:
        e = BY_ID.get(str(camera.get(key) or ""))
        if not e or e["category"] != key or (e["video_only"] and not video):
            continue
        parts.append(e["prompt"])
    return ", ".join(parts)
